export const PERMISSION_CATALOG = {
  'branches.read': 'View branches within authorized scope',
  'branches.manage': 'Create and manage branches within authorized scope',
  'users.read': 'View user accounts',
  'users.manage': 'Create and manage user accounts',
  'roles.read': 'View roles and permissions',
  'roles.manage': 'Manage roles and permissions',
  'students.read': 'View students within authorized scope',
  'students.manage': 'Manage students within authorized scope',
  'halaqas.read': 'View halaqas within authorized scope',
  'halaqas.manage': 'Manage halaqas within authorized scope',
  'academic_years.read': 'View academic years and terms within authorized scope',
  'academic_years.manage': 'Create and manage academic years and terms',
  'educational_plans.read': 'View educational plans within authorized scope',
  'educational_plans.manage': 'Create and manage educational plans',
  'attendance.read': 'View attendance within authorized scope',
  'attendance.write': 'Record attendance within authorized scope',
  'memorization.read': 'View memorization within authorized scope',
  'memorization.write': 'Record memorization within authorized scope',
  'revision.read': 'View revision records within authorized scope',
  'revision.write': 'Record revision records within authorized scope',
  'student_progress.read': 'View student progress and indicators within authorized scope',
  'exams.read': 'View exams within authorized scope',
  'exams.manage': 'Create and manage exams within authorized scope',
  'grades.read': 'View grades and exam results within authorized scope',
  'grades.write': 'Record and update grades and exam results within authorized scope',
  'grades.publish': 'Publish and unpublish grades and exam results',
  'student_evaluations.read': 'View student periodic evaluations within authorized scope',
  'student_evaluations.write': 'Record and manage student periodic evaluations',
  'field_visits.read': 'View field visits within authorized scope',
  'field_visits.write': 'Manage field visits within authorized scope',
  'evaluations.read': 'View evaluation reports within authorized scope',
  'evaluations.write': 'Record and submit evaluation reports within authorized scope',
  'evaluation_templates.read': 'View evaluation templates and criteria',
  'evaluation_templates.manage': 'Manage evaluation templates, axes, and criteria',
  'recommendations.read': 'View recommendations within authorized scope',
  'recommendations.write': 'Create and update recommendations and follow-ups within authorized scope',
  'supervisor_reports.read': 'View supervisor dashboards and summaries within authorized scope',
  'reports.read': 'View authorized reports',
  'reports.export': 'Export reports to PDF and CSV formats',
  'settings.manage': 'Manage forum settings',
  'audit.read': 'View audit records',
  'activities.read': 'View activities within authorized scope',
  'activities.manage': 'Create and manage activities within authorized scope',
  'competitions.read': 'View competitions within authorized scope',
  'competitions.manage': 'Create and manage competitions within authorized scope',
  'competition_results.manage': 'Record and publish competition results within authorized scope',
  'awards.read': 'View awards and student recognitions within authorized scope',
  'awards.manage': 'Create awards and grant awards to students within authorized scope',
  'shelf.read': 'View general shelf sections and published posts within authorized scope',
  'shelf.manage': 'Manage general shelf sections and posts within authorized scope',
  'shelf.publish': 'Create and publish content to general shelf',
  'shelf.permissions.manage': 'Manage publishing rules and author permissions for shelf sections',
  'admin_requests.read': 'View administrative requests within authorized scope',
  'admin_requests.create': 'Create and submit administrative requests',
  'admin_requests.review': 'Review, approve, or reject administrative requests',
  'admin_decisions.read': 'View administrative decisions within authorized scope',
  'admin_decisions.manage': 'Create, issue, and manage administrative decisions',
  'admin_alerts.read': 'View administrative alerts within authorized scope',
  'admin_alerts.manage': 'Manage and resolve administrative alerts',
  'admin_tasks.read': 'View administrative tasks and follow-ups within authorized scope',
  'admin_tasks.manage': 'Create, assign, and manage administrative tasks',
} as const;

export type PermissionCode = keyof typeof PERMISSION_CATALOG;

export const ROLE_PERMISSION_DEFAULTS: Record<string, readonly PermissionCode[]> = {
  GENERAL_MANAGER: Object.keys(PERMISSION_CATALOG) as PermissionCode[],
  EXECUTIVE_MANAGER: [
    'branches.read',
    'users.read',
    'roles.read',
    'students.read',
    'students.manage',
    'halaqas.read',
    'halaqas.manage',
    'academic_years.read',
    'educational_plans.read',
    'educational_plans.manage',
    'attendance.read',
    'memorization.read',
    'revision.read',
    'student_progress.read',
    'exams.read',
    'exams.manage',
    'grades.read',
    'grades.write',
    'grades.publish',
    'student_evaluations.read',
    'student_evaluations.write',
    'field_visits.read',
    'field_visits.write',
    'evaluations.read',
    'evaluations.write',
    'evaluation_templates.read',
    'evaluation_templates.manage',
    'recommendations.read',
    'recommendations.write',
    'supervisor_reports.read',
    'reports.read',
    'reports.export',
    'audit.read',
    'activities.read',
    'activities.manage',
    'competitions.read',
    'competitions.manage',
    'competition_results.manage',
    'awards.read',
    'awards.manage',
    'shelf.read',
    'shelf.manage',
    'shelf.publish',
    'shelf.permissions.manage',
    'admin_requests.read',
    'admin_requests.create',
    'admin_requests.review',
    'admin_decisions.read',
    'admin_decisions.manage',
    'admin_alerts.read',
    'admin_alerts.manage',
    'admin_tasks.read',
    'admin_tasks.manage',
  ],
  TEACHER: [
    'students.read',
    'halaqas.read',
    'educational_plans.read',
    'attendance.read',
    'attendance.write',
    'memorization.read',
    'memorization.write',
    'revision.read',
    'revision.write',
    'student_progress.read',
    'exams.read',
    'grades.read',
    'grades.write',
    'student_evaluations.read',
    'student_evaluations.write',
    'recommendations.read',
    'reports.read',
    'activities.read',
    'competitions.read',
    'awards.read',
    'shelf.read',
    'admin_requests.read',
    'admin_requests.create',
    'admin_decisions.read',
    'admin_tasks.read',
  ],
  TECHNICAL_SUPERVISOR: [
    'students.read',
    'halaqas.read',
    'academic_years.read',
    'educational_plans.read',
    'attendance.read',
    'memorization.read',
    'revision.read',
    'student_progress.read',
    'exams.read',
    'grades.read',
    'student_evaluations.read',
    'field_visits.read',
    'field_visits.write',
    'evaluations.read',
    'evaluations.write',
    'evaluation_templates.read',
    'recommendations.read',
    'recommendations.write',
    'supervisor_reports.read',
    'reports.read',
    'reports.export',
    'activities.read',
    'competitions.read',
    'awards.read',
    'shelf.read',
    'admin_requests.read',
    'admin_requests.create',
    'admin_decisions.read',
    'admin_alerts.read',
    'admin_tasks.read',
  ],
  STUDENT: [
    'educational_plans.read',
    'attendance.read',
    'memorization.read',
    'revision.read',
    'student_progress.read',
    'exams.read',
    'grades.read',
    'student_evaluations.read',
    'activities.read',
    'competitions.read',
    'awards.read',
    'shelf.read',
  ],
  PARENT: [
    'students.read',
    'educational_plans.read',
    'attendance.read',
    'memorization.read',
    'revision.read',
    'student_progress.read',
    'exams.read',
    'grades.read',
    'student_evaluations.read',
    'activities.read',
    'competitions.read',
    'awards.read',
    'shelf.read',
  ],
};
