class SurahInfo {
  final int number;
  final String name;
  final int ayahCount;
  final int juzStart;

  const SurahInfo({
    required this.number,
    required this.name,
    required this.ayahCount,
    required this.juzStart,
  });
}

class QuranData {
  static const List<SurahInfo> surahs = [
    SurahInfo(number: 1, name: 'الفاتحة', ayahCount: 7, juzStart: 1),
    SurahInfo(number: 2, name: 'البقرة', ayahCount: 286, juzStart: 1),
    SurahInfo(number: 3, name: 'آل عمران', ayahCount: 200, juzStart: 3),
    SurahInfo(number: 4, name: 'النساء', ayahCount: 176, juzStart: 4),
    SurahInfo(number: 5, name: 'المائدة', ayahCount: 120, juzStart: 6),
    SurahInfo(number: 6, name: 'الأنعام', ayahCount: 165, juzStart: 7),
    SurahInfo(number: 7, name: 'الأعراف', ayahCount: 206, juzStart: 8),
    SurahInfo(number: 8, name: 'الأنفال', ayahCount: 75, juzStart: 9),
    SurahInfo(number: 9, name: 'التوبة', ayahCount: 129, juzStart: 10),
    SurahInfo(number: 10, name: 'يونس', ayahCount: 109, juzStart: 11),
    SurahInfo(number: 11, name: 'هود', ayahCount: 123, juzStart: 11),
    SurahInfo(number: 12, name: 'يوسف', ayahCount: 111, juzStart: 12),
    SurahInfo(number: 13, name: 'الرعد', ayahCount: 43, juzStart: 13),
    SurahInfo(number: 14, name: 'إبراهيم', ayahCount: 52, juzStart: 13),
    SurahInfo(number: 15, name: 'الحجر', ayahCount: 99, juzStart: 14),
    SurahInfo(number: 16, name: 'النحل', ayahCount: 128, juzStart: 14),
    SurahInfo(number: 17, name: 'الإسراء', ayahCount: 111, juzStart: 15),
    SurahInfo(number: 18, name: 'الكهف', ayahCount: 110, juzStart: 15),
    SurahInfo(number: 19, name: 'مريم', ayahCount: 98, juzStart: 16),
    SurahInfo(number: 20, name: 'طه', ayahCount: 135, juzStart: 16),
    SurahInfo(number: 21, name: 'الأنبياء', ayahCount: 112, juzStart: 17),
    SurahInfo(number: 22, name: 'الحج', ayahCount: 78, juzStart: 17),
    SurahInfo(number: 23, name: 'المؤمنون', ayahCount: 118, juzStart: 18),
    SurahInfo(number: 24, name: 'النور', ayahCount: 64, juzStart: 18),
    SurahInfo(number: 25, name: 'الفرقان', ayahCount: 77, juzStart: 18),
    SurahInfo(number: 26, name: 'الشعراء', ayahCount: 227, juzStart: 19),
    SurahInfo(number: 27, name: 'النمل', ayahCount: 93, juzStart: 19),
    SurahInfo(number: 28, name: 'القصص', ayahCount: 88, juzStart: 20),
    SurahInfo(number: 29, name: 'العنكبوت', ayahCount: 69, juzStart: 20),
    SurahInfo(number: 30, name: 'الروم', ayahCount: 60, juzStart: 21),
    SurahInfo(number: 31, name: 'لقمان', ayahCount: 34, juzStart: 21),
    SurahInfo(number: 32, name: 'السجدة', ayahCount: 30, juzStart: 21),
    SurahInfo(number: 33, name: 'الأحزاب', ayahCount: 73, juzStart: 21),
    SurahInfo(number: 34, name: 'سبأ', ayahCount: 54, juzStart: 22),
    SurahInfo(number: 35, name: 'فاطر', ayahCount: 45, juzStart: 22),
    SurahInfo(number: 36, name: 'يس', ayahCount: 83, juzStart: 22),
    SurahInfo(number: 37, name: 'الصافات', ayahCount: 182, juzStart: 23),
    SurahInfo(number: 38, name: 'ص', ayahCount: 88, juzStart: 23),
    SurahInfo(number: 39, name: 'الزمر', ayahCount: 75, juzStart: 23),
    SurahInfo(number: 40, name: 'غافر', ayahCount: 85, juzStart: 24),
    SurahInfo(number: 41, name: 'فصلت', ayahCount: 54, juzStart: 24),
    SurahInfo(number: 42, name: 'الشورى', ayahCount: 53, juzStart: 25),
    SurahInfo(number: 43, name: 'الزخرف', ayahCount: 89, juzStart: 25),
    SurahInfo(number: 44, name: 'الدخان', ayahCount: 59, juzStart: 25),
    SurahInfo(number: 45, name: 'الجاثية', ayahCount: 37, juzStart: 25),
    SurahInfo(number: 46, name: 'الأحقاف', ayahCount: 35, juzStart: 26),
    SurahInfo(number: 47, name: 'محمد', ayahCount: 38, juzStart: 26),
    SurahInfo(number: 48, name: 'الفتح', ayahCount: 29, juzStart: 26),
    SurahInfo(number: 49, name: 'الحجرات', ayahCount: 18, juzStart: 26),
    SurahInfo(number: 50, name: 'ق', ayahCount: 45, juzStart: 26),
    SurahInfo(number: 51, name: 'الذاريات', ayahCount: 60, juzStart: 26),
    SurahInfo(number: 52, name: 'الطور', ayahCount: 49, juzStart: 27),
    SurahInfo(number: 53, name: 'النجم', ayahCount: 62, juzStart: 27),
    SurahInfo(number: 54, name: 'القمر', ayahCount: 55, juzStart: 27),
    SurahInfo(number: 55, name: 'الرحمن', ayahCount: 78, juzStart: 27),
    SurahInfo(number: 56, name: 'الواقعة', ayahCount: 96, juzStart: 27),
    SurahInfo(number: 57, name: 'الحديد', ayahCount: 29, juzStart: 27),
    SurahInfo(number: 58, name: 'المجادلة', ayahCount: 22, juzStart: 28),
    SurahInfo(number: 59, name: 'الحشر', ayahCount: 24, juzStart: 28),
    SurahInfo(number: 60, name: 'الممتحنة', ayahCount: 13, juzStart: 28),
    SurahInfo(number: 61, name: 'الصف', ayahCount: 14, juzStart: 28),
    SurahInfo(number: 62, name: 'الجمعة', ayahCount: 11, juzStart: 28),
    SurahInfo(number: 63, name: 'المنافقون', ayahCount: 11, juzStart: 28),
    SurahInfo(number: 64, name: 'التغابن', ayahCount: 18, juzStart: 28),
    SurahInfo(number: 65, name: 'الطلاق', ayahCount: 12, juzStart: 28),
    SurahInfo(number: 66, name: 'التحريم', ayahCount: 12, juzStart: 28),
    SurahInfo(number: 67, name: 'الملك', ayahCount: 30, juzStart: 29),
    SurahInfo(number: 68, name: 'القلم', ayahCount: 52, juzStart: 29),
    SurahInfo(number: 69, name: 'الحاقة', ayahCount: 52, juzStart: 29),
    SurahInfo(number: 70, name: 'المعارج', ayahCount: 44, juzStart: 29),
    SurahInfo(number: 71, name: 'نوح', ayahCount: 28, juzStart: 29),
    SurahInfo(number: 72, name: 'الجن', ayahCount: 28, juzStart: 29),
    SurahInfo(number: 73, name: 'المزمل', ayahCount: 20, juzStart: 29),
    SurahInfo(number: 74, name: 'المدثر', ayahCount: 56, juzStart: 29),
    SurahInfo(number: 75, name: 'القيامة', ayahCount: 40, juzStart: 29),
    SurahInfo(number: 76, name: 'الإنسان', ayahCount: 31, juzStart: 29),
    SurahInfo(number: 77, name: 'المرسلات', ayahCount: 50, juzStart: 29),
    SurahInfo(number: 78, name: 'النبأ', ayahCount: 40, juzStart: 30),
    SurahInfo(number: 79, name: 'النازعات', ayahCount: 46, juzStart: 30),
    SurahInfo(number: 80, name: 'عبس', ayahCount: 42, juzStart: 30),
    SurahInfo(number: 81, name: 'التكوير', ayahCount: 29, juzStart: 30),
    SurahInfo(number: 82, name: 'الانفطار', ayahCount: 19, juzStart: 30),
    SurahInfo(number: 83, name: 'المطففين', ayahCount: 36, juzStart: 30),
    SurahInfo(number: 84, name: 'الانشقاق', ayahCount: 25, juzStart: 30),
    SurahInfo(number: 85, name: 'البروج', ayahCount: 22, juzStart: 30),
    SurahInfo(number: 86, name: 'الطارق', ayahCount: 17, juzStart: 30),
    SurahInfo(number: 87, name: 'الأعلى', ayahCount: 19, juzStart: 30),
    SurahInfo(number: 88, name: 'الغاشية', ayahCount: 26, juzStart: 30),
    SurahInfo(number: 89, name: 'الفجر', ayahCount: 30, juzStart: 30),
    SurahInfo(number: 90, name: 'البلد', ayahCount: 20, juzStart: 30),
    SurahInfo(number: 91, name: 'الشمس', ayahCount: 15, juzStart: 30),
    SurahInfo(number: 92, name: 'الليل', ayahCount: 21, juzStart: 30),
    SurahInfo(number: 93, name: 'الضحى', ayahCount: 11, juzStart: 30),
    SurahInfo(number: 94, name: 'الشرح', ayahCount: 8, juzStart: 30),
    SurahInfo(number: 95, name: 'التين', ayahCount: 8, juzStart: 30),
    SurahInfo(number: 96, name: 'العلق', ayahCount: 19, juzStart: 30),
    SurahInfo(number: 97, name: 'القدر', ayahCount: 5, juzStart: 30),
    SurahInfo(number: 98, name: 'البينة', ayahCount: 8, juzStart: 30),
    SurahInfo(number: 99, name: 'الزلزلة', ayahCount: 8, juzStart: 30),
    SurahInfo(number: 100, name: 'العاديات', ayahCount: 11, juzStart: 30),
    SurahInfo(number: 101, name: 'القارعة', ayahCount: 11, juzStart: 30),
    SurahInfo(number: 102, name: 'التكاثر', ayahCount: 8, juzStart: 30),
    SurahInfo(number: 103, name: 'العصر', ayahCount: 3, juzStart: 30),
    SurahInfo(number: 104, name: 'الهمزة', ayahCount: 9, juzStart: 30),
    SurahInfo(number: 105, name: 'الفيل', ayahCount: 5, juzStart: 30),
    SurahInfo(number: 106, name: 'قريش', ayahCount: 4, juzStart: 30),
    SurahInfo(number: 107, name: 'الماعون', ayahCount: 7, juzStart: 30),
    SurahInfo(number: 108, name: 'الكوثر', ayahCount: 3, juzStart: 30),
    SurahInfo(number: 109, name: 'الكافرون', ayahCount: 6, juzStart: 30),
    SurahInfo(number: 110, name: 'النصر', ayahCount: 3, juzStart: 30),
    SurahInfo(number: 111, name: 'المسد', ayahCount: 5, juzStart: 30),
    SurahInfo(number: 112, name: 'الإخلاص', ayahCount: 4, juzStart: 30),
    SurahInfo(number: 113, name: 'الفلق', ayahCount: 5, juzStart: 30),
    SurahInfo(number: 114, name: 'الناس', ayahCount: 6, juzStart: 30),
  ];

  static SurahInfo getByNumber(int number) {
    if (number < 1 || number > 114) return surahs[0];
    return surahs[number - 1];
  }

  static String getSurahName(int? number) {
    if (number == null || number < 1 || number > 114) return 'غير محدد';
    return surahs[number - 1].name;
  }
}
